// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createTenant = `-- name: CreateTenant :exec
INSERT INTO tenants (id, name, slug, domain, settings, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateTenantParams struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Slug      string          `json:"slug"`
	Domain    sql.NullString  `json:"domain"`
	Settings  json.RawMessage `json:"settings"`
	IsActive  bool            `json:"is_active"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) error {
	_, err := q.db.ExecContext(ctx, createTenant,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Domain,
		arg.Settings,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteTenant = `-- name: DeleteTenant :execrows
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTenant, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, domain, settings, is_active, created_at, updated_at
FROM tenants WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, domain, settings, is_active, created_at, updated_at
FROM tenants WHERE slug = $1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenant = `-- name: UpdateTenant :execrows
UPDATE tenants SET name = $2, domain = $3, settings = $4, is_active = $5, updated_at = $6
WHERE id = $1
`

type UpdateTenantParams struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Domain    sql.NullString  `json:"domain"`
	Settings  json.RawMessage `json:"settings"`
	IsActive  bool            `json:"is_active"`
	UpdatedAt time.Time       `json:"updated_at"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTenant,
		arg.ID,
		arg.Name,
		arg.Domain,
		arg.Settings,
		arg.IsActive,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
