// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type AuditLog struct {
	ID           uuid.UUID      `json:"id"`
	RequestID    string         `json:"request_id"`
	UserID       uuid.NullUUID  `json:"user_id"`
	UserEmail    sql.NullString `json:"user_email"`
	Method       string         `json:"method"`
	Path         string         `json:"path"`
	StatusCode   int32          `json:"status_code"`
	DurationMs   int64          `json:"duration_ms"`
	Ip           string         `json:"ip"`
	UserAgent    string         `json:"user_agent"`
	RequestBody  sql.NullString `json:"request_body"`
	ResponseSize int32          `json:"response_size"`
	CreatedAt    time.Time      `json:"created_at"`
	TenantID     string         `json:"tenant_id"`
}

type ErrorLog struct {
	ID          uuid.UUID      `json:"id"`
	RequestID   string         `json:"request_id"`
	UserID      uuid.NullUUID  `json:"user_id"`
	UserEmail   sql.NullString `json:"user_email"`
	Level       string         `json:"level"`
	Message     string         `json:"message"`
	Error       string         `json:"error"`
	StackTrace  string         `json:"stack_trace"`
	Method      string         `json:"method"`
	Path        string         `json:"path"`
	StatusCode  int32          `json:"status_code"`
	Ip          string         `json:"ip"`
	UserAgent   string         `json:"user_agent"`
	RequestBody sql.NullString `json:"request_body"`
	Metadata    []byte         `json:"metadata"`
	CreatedAt   time.Time      `json:"created_at"`
	TenantID    string         `json:"tenant_id"`
}

type Permission struct {
	ID          uuid.UUID    `json:"id"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	Resource    string       `json:"resource"`
	Action      string       `json:"action"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
	TenantID    string       `json:"tenant_id"`
}

type RefreshToken struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Role struct {
	ID          uuid.UUID    `json:"id"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
	TenantID    string       `json:"tenant_id"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
	CreatedAt    time.Time `json:"created_at"`
	TenantID     string    `json:"tenant_id"`
}

type Tenant struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Slug      string          `json:"slug"`
	Domain    sql.NullString  `json:"domain"`
	Settings  json.RawMessage `json:"settings"`
	IsActive  bool            `json:"is_active"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type Todo struct {
	ID          uuid.UUID    `json:"id"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	Completed   bool         `json:"completed"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
	TenantID    string       `json:"tenant_id"`
}

type User struct {
	ID                   uuid.UUID      `json:"id"`
	Email                string         `json:"email"`
	Password             string         `json:"password"`
	Name                 string         `json:"name"`
	IsActive             bool           `json:"is_active"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	DeletedAt            sql.NullTime   `json:"deleted_at"`
	FailedLoginAttempts  int32          `json:"failed_login_attempts"`
	EmailVerified        sql.NullBool   `json:"email_verified"`
	EmailVerifyToken     sql.NullString `json:"email_verify_token"`
	EmailVerifyExpires   sql.NullTime   `json:"email_verify_expires"`
	PasswordResetToken   sql.NullString `json:"password_reset_token"`
	PasswordResetExpires sql.NullTime   `json:"password_reset_expires"`
	TenantID             string         `json:"tenant_id"`
	EmailVerifiedAt      sql.NullTime   `json:"email_verified_at"`
}

type UserAddress struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	Label      string    `json:"label"`
	IsDefault  bool      `json:"is_default"`
	Street     string    `json:"street"`
	City       string    `json:"city"`
	State      string    `json:"state"`
	PostalCode string    `json:"postal_code"`
	Country    string    `json:"country"`
}

type UserCredential struct {
	UserID       uuid.UUID    `json:"user_id"`
	PasswordHash string       `json:"password_hash"`
	LastLoginAt  sql.NullTime `json:"last_login_at"`
}

type UserPreference struct {
	UserID      uuid.UUID       `json:"user_id"`
	Preferences json.RawMessage `json:"preferences"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type UserProfile struct {
	UserID    uuid.UUID      `json:"user_id"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	Phone     sql.NullString `json:"phone"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	Timezone  string         `json:"timezone"`
	Locale    string         `json:"locale"`
	Bio       sql.NullString `json:"bio"`
}

type UserRole struct {
	UserID    uuid.UUID `json:"user_id"`
	RoleID    uuid.UUID `json:"role_id"`
	CreatedAt time.Time `json:"created_at"`
	TenantID  string    `json:"tenant_id"`
}

type UserSecurity struct {
	UserID        uuid.UUID      `json:"user_id"`
	LoginAttempts int32          `json:"login_attempts"`
	LockedUntil   sql.NullTime   `json:"locked_until"`
	MfaEnabled    bool           `json:"mfa_enabled"`
	MfaSecret     sql.NullString `json:"mfa_secret"`
}

type UserSession struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	RefreshTokenHash sql.NullString `json:"refresh_token_hash"`
	DeviceInfo       string         `json:"device_info"`
	IpAddress        string         `json:"ip_address"`
	UserAgent        string         `json:"user_agent"`
	ExpiresAt        sql.NullTime   `json:"expires_at"`
	LastUsedAt       time.Time      `json:"last_used_at"`
	RevokedAt        sql.NullTime   `json:"revoked_at"`
	CreatedAt        time.Time      `json:"created_at"`
}

type UserSocialLink struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	Provider      string         `json:"provider"`
	ProviderID    string         `json:"provider_id"`
	ProviderEmail sql.NullString `json:"provider_email"`
	AvatarUrl     sql.NullString `json:"avatar_url"`
	CreatedAt     time.Time      `json:"created_at"`
}

type UserToken struct {
	ID         uuid.UUID      `json:"id"`
	UserID     uuid.UUID      `json:"user_id"`
	TokenType  string         `json:"token_type"`
	TokenHash  sql.NullString `json:"token_hash"`
	ExpiresAt  sql.NullTime   `json:"expires_at"`
	ConsumedAt sql.NullTime   `json:"consumed_at"`
	CreatedAt  time.Time      `json:"created_at"`
}
