// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todo.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createTodo = `-- name: CreateTodo :exec
INSERT INTO todos (id, title, description, completed, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateTodoParams struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Completed   bool      `json:"completed"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) error {
	_, err := q.db.ExecContext(ctx, createTodo,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getTodoByID = `-- name: GetTodoByID :one
SELECT id, title, description, completed, created_at, updated_at, deleted_at
FROM todos
WHERE id = $1 AND deleted_at IS NULL
`

type GetTodoByIDRow struct {
	ID          uuid.UUID    `json:"id"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	Completed   bool         `json:"completed"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
}

func (q *Queries) GetTodoByID(ctx context.Context, id uuid.UUID) (GetTodoByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTodoByID, id)
	var i GetTodoByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteTodo = `-- name: SoftDeleteTodo :execrows
UPDATE todos
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTodo(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteTodo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTodo = `-- name: UpdateTodo :execrows
UPDATE todos
SET title = $2, description = $3, completed = $4, updated_at = $5
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateTodoParams struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Completed   bool      `json:"completed"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTodo,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
