global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "go-codebase"
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis_exporter:9121"]

  - job_name: "nats"
    static_configs:
      - targets: ["nats:8222"]

  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"]
