apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-codebase
  namespace: go-codebase
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - go-codebase.example.com
      secretName: go-codebase-tls
  rules:
    - host: go-codebase.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-codebase
                port:
                  number: 80
