apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: go-codebase

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/idts-lab/go-codebase
    newTag: latest
